### PR TITLE
fix memory leak in XKeyboard::build_layout

### PR DESCRIPTION
**Pull request by szaszm**
XkbRF_VarDefsRec seems to be intended to be used only through XkbRF_RulesRec.
It includes dynamically allocated C string, but provides no direct
cleanup method. This commit adds custom cleanup as a workaround.

A proper cleanup would complicate the code even more, so this is just a bandaid to avoid the leak while keeping the code relatively compact.

XkbRF_VarDefsRec: https://github.com/freedesktop/xorg-libxkbfile/blob/master/include/X11/extensions/XKBrules.h
cleanup in khurshid-alam/Unity-Settings-Daemon: https://github.com/khurshid-alam/Unity-Settings-Daemon/blob/7135a08b39e17401338232ee3f0309582dd31202/plugins/keyboard/gsd-xkb-utils.c#L78

### CODE REVIEW

**Comment by grwlf** [comment]
Good catch, thanks! Could you suggest a way to protect the code from possible failures due to XkbRF_VarDefsRec design changes?

**Comment by grwlf** [comment]
Note, filed a bug https://bugs.freedesktop.org/show_bug.cgi?id=110696

**Comment by szaszm** [comment]
I've spent an additional 2 hours googling a proper way to query the keyboard layout, still no success. I suggest we wait for a reply on the upstream bug report you just created.
Possibly interesting findings:
- It seems the X server doesn't have such a setting as layout, therefore it doesn't make sense to query one. It seems to be a write-only abstraction provided by XKB. https://bugzilla.gnome.org/show_bug.cgi?id=152105 
- A similar project is also full of leaks: https://github.com/nonpop/xkblayout-state
- "three people on this earth understand X input": https://people.freedesktop.org/~daniels/lca2013-wayland-x11.pdf (page 70)
- Here, both the XkbGetKeyboard-based method and the XkbRF_GetNamesProp-based one is leaky: https://gist.github.com/fikovnik/ef428e82a26774280c4fdf8f96ce8eeb
- See also my thin wrapper, where I've used the same workaround for XkbRF_GetNamesProp, but the current XkbGetKeyboard-based method is still leaking: https://gist.github.com/szaszm/05e6a08e6b0e56149338e6172253c569

**Comment by grwlf** [comment]
OK, thank you. I merge this PR, but leave the issue open.

**Pull request merged**
